extends Node

const ALPHABET = "△○□"

const EMPTY_TILE_VALUE = "_"

const MIN_SOLUTION_LENGTH = MIN_RULE_LENGTH

const PENALTY_EMPTY_TILE = -5

const BASE_SCORE = 10

const MAX_SOLUTION_LENGTH = 10

const MIN_SCORE = 0

const MAX_SCORE = 500

const NORMALIZED_START_SCORE: float = .3

const SCORE_DECREMENT_PER_ROUND_INITIAL := 20

const MIN_RULES = 2

const MAX_RULES = 2

const MIN_VALUE_LENGTH = 1

const MAX_VALUE_LENGTH = 3

const MIN_RULE_LENGTH = 2

const MAX_RULE_LENGTH = 2

const USE_SPEECH_TIMER := true

const USE_SPEECH_TIME := 25.0

const CHILLIN_THRESH := 300

const DREAD_THRESH := 200
