extends Node

const ALPHABET = "△○□"

const EMPTY_TILE_VALUE = "_"

const MIN_SOLUTION_LENGTH = MIN_RULE_LENGTH

const PENALTY_EMPTY_TILE = -5

const BASE_SCORE = 10

const MIN_SCORE = 0

const MAX_SCORE = 500

const NORMALIZED_START_SCORE: float = .2

const SCORE_DECREMENT_PER_ROUND_INITIAL := 20

const MIN_RULES = 2

const MAX_RULES = 2

const MIN_VALUE_LENGTH = 1

const MAX_VALUE_LENGTH = 3

const MIN_RULE_LENGTH = 2

const MAX_RULE_LENGTH = 2

const USE_SPEECH_TIMER := true

const SPEECH_TIME := 15.0

const CHILLIN_THRESH := 300

const DREAD_THRESH := 200

# SCORING

const PENALTY_TILE_SCORE = -1

const PENALTY_TABLE = [
	PENALTY_TILE_SCORE * 0,
	PENALTY_TILE_SCORE * 0,
	PENALTY_TILE_SCORE * 0,
	PENALTY_TILE_SCORE * 1,
	PENALTY_TILE_SCORE * 1,
	PENALTY_TILE_SCORE * 2,
	PENALTY_TILE_SCORE * 4,
	PENALTY_TILE_SCORE * 8,
	PENALTY_TILE_SCORE * 16,
	PENALTY_TILE_SCORE * 32,
]

const PENALTY_CHARACTER_LOOKUP = {
	PENALTY_TABLE[0]: "0",
	PENALTY_TABLE[3]: "1",
	PENALTY_TABLE[5]: "2",
	PENALTY_TABLE[6]: "3",
	PENALTY_TABLE[7]: "4",
	PENALTY_TABLE[8]: "5",
	PENALTY_TABLE[9]: "6",
}

const PENALTY_SCORE_LOOKUP = {
	"0": PENALTY_TABLE[0],
	"1": PENALTY_TABLE[3],
	"2": PENALTY_TABLE[5],
	"3": PENALTY_TABLE[6],
	"4": PENALTY_TABLE[7],
	"5": PENALTY_TABLE[8],
	"6": PENALTY_TABLE[9],
}
